[project]
name = "mcp-integration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "fastmcp>=2.10.2",
    "semantic-kernel>=1.32.2",
]
